//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace env.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class star_energy_enviroEntities : DbContext
    {
        public star_energy_enviroEntities()
            : base("name=star_energy_enviroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<source_of_waste> source_of_waste { get; set; }
        public DbSet<waste_hazardous> waste_hazardous { get; set; }
        public DbSet<satuan_unit> satuan_unit { get; set; }
        public DbSet<type_of_waste> type_of_waste { get; set; }
        public DbSet<non_hazardous_record> non_hazardous_record { get; set; }
        public DbSet<hazardous_record> hazardous_record { get; set; }
    }
}
