//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace env.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class graphic_parameter
    {
        public graphic_parameter()
        {
            this.graphic_data = new HashSet<graphic_data>();
        }
    
        public int id { get; set; }
        public string parameter { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual ICollection<graphic_data> graphic_data { get; set; }
    }
}
